name: Weather Every 10 Minutes

on:
  schedule:
    - cron: '*/10 * * * *' # Runs every 10 minutes

jobs:
  run-weather-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run my weather script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SERVICE_ROLE_KEY: ${{ secrets.SERVICE_ROLE_KEY }}
          API_KEY: ${{ secrets.API_KEY }}
        run: python weather_last.py
